plugins:
  - jekyll-seo-tag

title: Ali Saif
logo: /assets/img/profile-picture.jpg
logo_local: 
    image: /assets/img/profile-picture.jpg
    symbol: "&Lambda;"
    text: "Ali <span>Saif</span>"

url: https://integracore.tech

tagline: Contract Consultant | Technical Architect | Startup Advisor
description: Supporting FinTech and EdTech Startups, Engineering and Quant R&D Teams, Professional Services Firms and Consultancies with Technical and Strategic Advisory, Corporate & Technical Training, Data, Software, and Integrations Engineering services.

twitter:
  username: integracore2
  card: summary

social:
  name: Ali Saif
  links:
    - https://twitter.com/integracore2
    - https://www.linkedin.com/in/ali-saif
    - https://github.com/integracore2

show_downloads: false
#paginate: 5

google_recaptcha:
    site_key: 6LeNlGcgAAAAAI-k3G6BDl_dixxmXKMbIFS8WZih

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: