title: Ali Saif
logo: /assets/img/profile-picture.jpg
description: Hands-On Technical Architect | Startup Advisor
show_downloads: false
#paginate: 5
google_analytics:
# theme: jekyll-theme-integracore2-light
author:
    name: Ali Saif
    bio: Passionate lifetime learner and problem-solver who loves being thrown in the deep end, thrives on continuous improvement, eliminating inefficiencies and enabling ideal outcomes.
    darwin_plf: https://www.darwinex.com/darwin/PLF?detail_view=true
    darwin_lzl: https://www.darwinex.com/darwin/LZL?detail_view=true
    darwin_icx: https://www.darwinex.com/darwin/ICX?detail_view=true
    darwin_nfx: https://www.darwinex.com/darwin/NFX?detail_view=true
    twitter: http://twitter.com/integracore2
    linkedin: https://www.linkedin.com/in/ali-saif/
    github: https://github.com/integracore2

datacamp: 
    profile: https://www.datacamp.com/profile/integracore

udacity:
    aitrading: https://confirm.udacity.com/5DVTP4V7

aws:
    ccp: https://www.credly.com/badges/bb4a9846-1b3d-4df1-a104-ba62e2835386?source=linked_in_profile
    well_architected_framework: https://aws.amazon.com/architecture/well-architected/

linkedin_image_repo: ./assets/img/linkedin-recommendations/

linkedin_profiles:
    persons:
        alicia_ortega:
            name: Alicia Ortega Roy
            url: https://www.linkedin.com/in/alicia-o-46b4b937
            role: Head of Marketing @ Darwinex
            image: alicia-ortega-hod-mkt-darwinex.jpg
            recommendation: <p>Ali, an intelligent, kind, patient and humble man whose leadership mantra is “support them but let them grow by themselves”.</p><p>You really make people think on their own and push them to give their best, always present but not interfering, a colleague always willing to help.</p><p>You’ve shown an admiring resilience at times of personal difficulties, always with a smile in your face, this is really one of the things that defines you, and for which you should be most proud.</p><p>It’s been a great pleasure working by your side, pushing our projects together and collaborating in our, sometimes, never-ending meetings 😂</p><p>Keep the smile, the kindness and the supportive spirit always with you and THANKS for being there when I needed it. A topeeeeee!!!!</p>
        martyn_tinsley:
            name: Martyn Tinsley
            url: https://www.linkedin.com/in/martyntinsley
            role: Director @ Trade Like A Machine Ltd
            image: martyn-tinsley-tlam.jpg
            recommendation: <p>I've had the pleasure of working under Ali's leadership for nearly two years now. His drive and enthusiasm, combined with his huge range of diverse talents and knowledge mean that he's someone I look up to and admire very much.</p><p>He exhibits a considered approach, and always seems to seek out creative solutions to problems.</p><p>Not only does Ali use his skills and knowledge to great effect in his own work, but he's always been willing to share his time and experience to help those around him - something that I have benefited from extensively.</p><p>I look forward to learning more from Ali as we work together in the future.</p>
        paula_romero:
            name: Paula Romero
            url: https://www.linkedin.com/in/pauromeropau
            role: Frontend Engineer @ Darwinex
            image: paula-romero-fe-eng-darwinex.jpg
            recommendation: <p>I have had the pleasure of working with Ali in the Marketing Department of Darwinex.</p><p>Ali has demonstrated from the very first day his amazing team management skills. He is a born leader, a person who inspires and motivates even in the most complicated moments.</p><p>He really believes in talent and has fully trusted in the ability of the team, allowing all of us to grow and learn a lot at his side.</p><p>People like his are hard to come by, someone able to transform really complex ideas into tiny simple concepts, easy to understand and manage.</p><p>Thank you so much for being my team mate,</p><p>Ka-POW Pau.</p>
        enrique_bm:
            name: Enrique Basañez Mercader
            url: https://www.linkedin.com/in/enriquebasanez
            role: Java Architect & Developer @ Darwinex
            image: enrique-bm-darwinex.jpg
            recommendation: <p>Ali is a living, caring and charming encyclopedia.</p><p>He is one of the most knowledgeable and experienced data scientist and algorithmic trader I know.</p><p>Here at Darwinex Ali has created a top experts department in Machine Learning, and is greatlty contributing to develop Darwinex network.</p><p>Although his busy agenda, Ali makes time to help everyone and is always open to receive new ideas.</p><p>Having such and experiece as Developer, Architect, Teacher, Data Scientist and Quantitative Trader makes him very keen in overcoming any challenge with a business oriented point of view.</p><p>It a pleasure and a privilege to work with him.</p>
        isabel_mf:
            name: Isabel Maldonado
            url: https://www.linkedin.com/in/isabelmaldonado
            role: Senior Graphic Design Specialist @ Darwinex
            image: isabel-mf-darwinex.jpg
            recommendation: <p>Ali is one of the best team leaders that I've had the opportunity to work with.</p><p>His charisma and kind personality make the work environment comfortable for all the team. Also, he knows a lot (A LOT), and he is not afraid to share that knowledge to help you improve your ideas.</p><p>As a team member, what I appreciated the most were his listening skills because that made me feel more confident about my work and wasn't afraid to share ideas with the team.</p><p>Thanks, Ali, for all your advice and patience :D!</p>
        eriz_zarate:
            name: Eriz Zárate
            url: https://www.linkedin.com/in/eriz-zarate
            role: CEO @ SoundIt & Zárate-Mateo Algorithmic Systems
            image: eriz-zarate-soundit.jpg
            recommendation: <p>Ali has been one of the best team leaders (if not the best) I have ever had.</p><p>Creative, understanding, hard-working, dynamic, and very intelligent, both in team management and at a technical level.</p><p>Always looking for ways to move forward and optimize processes, focusing on the skills of the teammate to achieve global success.</p><p>Definitely, someone who would always listen first and consult for any adventure.</p>
        jesus_bermudo:
            name: Jesús Bermudo Cruz
            url: https://www.linkedin.com/in/jesusbermudocruz
            role: Backend Software Engineer @ Darwinex
            image: jesus-bermudo-darwinex.jpg
            recommendation: <p>Ali turns everything he touch into Gold.</p><p>Such awesome positive enthusiasm and passion for his job is really strange these days in this world.</p><p>Always with a smile, very opened and charm with everyone in the company.</p><p>It's absolutely amazing having Ali on our side.</p>

client_image_repo: ./assets/img/clients/

clients:
    companies:
        zaratemateo:
            name: Zárate-Mateo Algorithmic Systems
            image: zarate-mateo-algorithmic-systems.png
            url: https://www.zaratemateo.com/
        iqlink:
            name: iQlink Limited
            image: iqlink.png
            url: https://www.iqlink.co.uk/
        packt:
            name: Packt Publishing
            image: packt-publishing.png
            url: https://www.packtpub.com/
        tradologics:
            name: Tradologics
            image: tradologics.png
            url: https://www.tradologics.com/
        darwinex:
            name: Darwinex
            image: darwinex.jpg
            url: https://www.darwinex.com/
        capriva:
            name: Capriva Asset Management
            image: capriva.png
            url: https://www.capriva.io/
        mitmedialab:
            name: MIT Media Lab
            image: mit-media-lab.png
            url: https://www.media.mit.edu/
        quantinsti:
            name: QuantInsti - Algorithmic Trading
            image: quantinsti.png
            url: https://www.quantinsti.com/
        tlam:
            name: Trade Like A Machine Ltd
            image: trade-like-a-machine.jpg
            url: https://www.tradelikeamachine.com/
        finbou:
            name: Finbou AG
            image: finbou.jpg
            url: https://www.finbou.com/
        sersansistemas:
            name: Sersan Sistemas S.L.
            image: sersan-sistemas.jpg
            url: https://www.sersansistemas.com/
        accuratequant:
            name: Accurate Quant - Quant Investment Solutions
            image: accurate-quant.jpg
            url: https://accuratequant.com/
        meridiana:
            name: Meridiana - Multi Family Office
            image: meridiana.png
            url: http://meridiana-mfo.com/
        nexdegree:
            name: NexDegree
            image: nexdegree.jpg
            url: https://www.nexdegree.com/
        tekcellent:
            name: Tekcellent Private Limited
            image: tekcellent.jpg
            url: https://www.tekcellent.com/
        albemarle:
            name: Albemarle Independent colleague
            image: albemarle.png
            url: https://www.albemarle.org.uk/

contact_form:
    action_url: https://docs.google.com/forms/u/0/d/e/1FAIpQLSdaB2yDCTffCr6B3DMn76spp4Uy7H6LDNnGgFsGDCgnQVq1rw/formResponse
    input_firstname: entry.2005620554
    input_email: entry.1045781291
    input_subject: entry.1065046570
    input_message: entry.839337160

google_recaptcha:
    site_key: 6LeNlGcgAAAAAI-k3G6BDl_dixxmXKMbIFS8WZih

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: