title: Saif (integracore2)
logo: /assets/img/logo.png
description: Full-Stack Data Scientist, Quant Trader, DARWIN Provider & Growth Hacker @ Darwinex (www.darwinex.com)
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
author:
    name: Saif (integracore2)