title: Saif (integracore2)
logo: /assets/img/profile-picture.jpg
description: Full-Stack Data Scientist, Quant Trader, DARWIN Provider & Growth Hacker @ Darwinex (www.darwinex.com)
show_downloads: false
paginate: 5
google_analytics:
theme: jekyll-theme-minimal
author:
    name: Saif (integracore2)
    darwin_plf: https://www.darwinex.com/darwin/PLF.4.1/
    darwin_lzl: https://www.darwinex.com/darwin/LZL.4.23/
    darwin_icx: https://www.darwinex.com/darwin/ICX.4.2/
    twitter: http://twitter.com/integracore2
    linkedin: https://www.linkedin.com/in/ali-saif/
# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: integracore-io