title: Ali Saif
logo: 
    image: /assets/img/profile-picture.jpg
    url: 
    symbol: "&Lambda;"
    text: "Ali <span>Saif</span>"
description: Technical Architect | Trainer | Startup Advisor
show_downloads: false
#paginate: 5
google_analytics:
# theme: jekyll-theme-integracore2-light
author:
    name: Ali Saif
    bio2: Supporting FinTech and EdTech Startups, Engineering and Quant R&D Teams, Professional Services Firms and Consultancies with Technical and Strategic Advisory, Corporate & Technical Training, Data, Software, and Integrations Engineering services.
    bio: Passionate lifetime learner and problem-solver who loves being thrown in the deep end, thrives on continuous improvement, eliminating inefficiencies and enabling ideal outcomes.
    darwin_plf: https://www.darwinex.com/darwin/PLF?detail_view=true
    darwin_lzl: https://www.darwinex.com/darwin/LZL?detail_view=true
    darwin_icx: https://www.darwinex.com/darwin/ICX?detail_view=true
    darwin_nfx: https://www.darwinex.com/darwin/NFX?detail_view=true
    twitter: http://twitter.com/integracore2
    linkedin: https://www.linkedin.com/in/ali-saif/
    github: https://github.com/integracore2
    roles:
        - Technical Architect & Trainer
        - Multi-Cloud Solutions Architect
        - Software Engineer & Developer Advocate
        - Startup Advisor & Corporate Trainer
        - Buy-Side Quant & Algorithmic Trader
    datacamp: 
        profile: https://www.datacamp.com/profile/integracore
    udacity:
        aitrading: https://confirm.udacity.com/5DVTP4V7
    aws:
        ccp: https://www.credly.com/badges/bb4a9846-1b3d-4df1-a104-ba62e2835386?source=linked_in_profile
        well_architected_framework: https://aws.amazon.com/architecture/well-architected/

google_recaptcha:
    site_key: 6LeNlGcgAAAAAI-k3G6BDl_dixxmXKMbIFS8WZih

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: