title: Ali Saif
logo: /assets/img/profile-picture.jpg
description: Hands-On Technical Architect | Startup Advisor
show_downloads: false
#paginate: 5
google_analytics:
# theme: jekyll-theme-integracore2-light
author:
    name: Ali Saif
    bio: Passionate lifetime learner and problem-solver who loves being thrown in the deep end, thrives on continuous improvement, eliminating inefficiencies and enabling ideal outcomes.
    darwin_plf: https://www.darwinex.com/darwin/PLF?detail_view=true
    darwin_lzl: https://www.darwinex.com/darwin/LZL?detail_view=true
    darwin_icx: https://www.darwinex.com/darwin/ICX?detail_view=true
    darwin_nfx: https://www.darwinex.com/darwin/NFX?detail_view=true
    twitter: http://twitter.com/integracore2
    linkedin: https://www.linkedin.com/in/ali-saif/
    github: https://github.com/integracore2
datacamp: 
    profile: https://www.datacamp.com/profile/integracore
udacity:
    aitrading: https://confirm.udacity.com/5DVTP4V7
aws:
    ccp: https://www.credly.com/badges/bb4a9846-1b3d-4df1-a104-ba62e2835386?source=linked_in_profile
    well_architected_framework: https://aws.amazon.com/architecture/well-architected/
linkedin_profile_images:
    image_repo: /assets/img/linkedin-recommendations/
    alicia_ortega: alicia-ortega-hod-mkt-darwinex.jpg
    paula_romero: paula-romero-fe-eng-darwinex.jpg
    isabel_mf: isabel-mf-darwinex.jpg
    eriz_zarate: eriz-zarate-soundit.jpg
    jesus_bermudo: jesus-bermudo-darwinex.jpg
    enrique_bm: enrique-bm-darwinex.jpg
    martyn_tinsley: martyn-tinsley-tlam.jpg
linkedin_profile_names:
    alicia_ortega: Alicia Ortega
    paula_romero: Paula Romero
    isabel_mf: Isabel Maldonado
    eriz_zarate: Eriz Zárate
    jesus_bermudo: Jesás Bermudo Cruz
    enrique_bm: Enrique Basañez Mercader
    martyn_tinsley: Martyn Tinsley
linkedin_profile_recommendations:
    alicia_ortega: <p>Ali, an intelligent, kind, patient and humble man whose leadership mantra is “support them but let them grow by themselves”.</p><p>You really make people think on their own and push them to give their best, always present but not interfering, a colleague always willing to help.</p><p>You’ve shown an admiring resilience at times of personal difficulties, always with a smile in your face, this is really one of the things that defines you, and for which you should be most proud.</p><p>It’s been a great pleasure working by your side, pushing our marketing projects together and collaborating in our, sometimes, never-ending meetings 😂</p><p>Keep the smile, the kindness and the supportive spirit always with you and THANKS for being there when I needed it. A topeeeeee!!!!</p>
    paula_romero: <p>I have had the pleasure of working with Ali in the Marketing Department of Darwinex.</p><p>Ali has demonstrated from the very first day his amazing team management skills. He is a born leader, a person who inspires and motivates even in the most complicated moments.</p><p>He really believes in talent and has fully trusted in the ability of the team, allowing all of us to grow and learn a lot at his side.</p><p>People like his are hard to come by, someone able to transform really complex ideas into tiny simple concepts, easy to understand and manage.</p><p>Thank you so much for being my team mate,</p><p>Ka-POW Pau.</p>
    isabel_mf: --
    eriz_zarate: --
    jesus_bermudo: --
    enrique_bm: --
    martyn_tinsley: --
linkedin_profile_firms:
    alicia_ortega: Head of Marketing @ Darwinex
    paula_romero: Senior Frontend Engineer @ Darwinex
    isabel_mf: Senior Graphic Design Specialist @ Darwinex
    eriz_zarate: CEO @ SoundIt
    jesus_bermudo: Backend Software Engineer @ Darwinex
    enrique_bm: Java Architect & Developer @ Darwinex
    martyn_tinsley: Director @ Trade Like A Machine Ltd
linkedin_profile_urls:
    alicia_ortega: https://www.linkedin.com/in/alicia-o-46b4b937
    paula_romero: https://www.linkedin.com/in/pauromeropau
    isabel_mf: https://www.linkedin.com/in/isabelmaldonado
    eriz_zarate: https://www.linkedin.com/in/eriz-zarate
    jesus_bermudo: https://www.linkedin.com/in/jesusbermudocruz
    enrique_bm: https://www.linkedin.com/in/enriquebasanez
    martyn_tinsley: https://www.linkedin.com/in/martyntinsley
contact_form:
    action_url: https://docs.google.com/forms/u/0/d/e/1FAIpQLSdaB2yDCTffCr6B3DMn76spp4Uy7H6LDNnGgFsGDCgnQVq1rw/formResponse
    input_firstname: entry.2005620554
    input_email: entry.1045781291
    input_subject: entry.1065046570
    input_message: entry.839337160
google_recaptcha:
    site_key: 6LeNlGcgAAAAAI-k3G6BDl_dixxmXKMbIFS8WZih
# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: