title: Ali Saif
logo: /assets/img/profile-picture.jpg
description: Hands-On Technical Architect | Startup Advisor
show_downloads: false
#paginate: 5
google_analytics:
# theme: jekyll-theme-integracore2-light
author:
    name: Ali Saif
    bio: Passionate lifetime learner and problem-solver who loves being thrown in the deep end, thrives on continuous improvement, eliminating inefficiencies and enabling ideal outcomes.
    darwin_plf: https://www.darwinex.com/darwin/PLF?detail_view=true
    darwin_lzl: https://www.darwinex.com/darwin/LZL?detail_view=true
    darwin_icx: https://www.darwinex.com/darwin/ICX?detail_view=true
    darwin_nfx: https://www.darwinex.com/darwin/NFX?detail_view=true
    twitter: http://twitter.com/integracore2
    linkedin: https://www.linkedin.com/in/ali-saif/
contact_form:
    action_url: https://docs.google.com/forms/u/0/d/e/1FAIpQLSdaB2yDCTffCr6B3DMn76spp4Uy7H6LDNnGgFsGDCgnQVq1rw/formResponse
    input_firstname: entry.2005620554
    input_email: emailAddress
    input_subject: entry.1065046570
    input_message: entry.839337160
google_recaptcha:
    site_key: 6LeNlGcgAAAAAI-k3G6BDl_dixxmXKMbIFS8WZih
# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: