title: Ali Saif
logo: /assets/img/profile-picture.jpg
description: Hands-On Technical Architect | Startup Advisor
show_downloads: false
#paginate: 5
google_analytics:
# theme: jekyll-theme-integracore2-light
author:
    name: Ali Saif
    bio: Passionate lifetime learner and problem-solver who loves being thrown in the deep end, thrives on continuous improvement, eliminating inefficiencies and enabling ideal outcomes.
    darwin_plf: https://www.darwinex.com/darwin/PLF?detail_view=true
    darwin_lzl: https://www.darwinex.com/darwin/LZL?detail_view=true
    darwin_icx: https://www.darwinex.com/darwin/ICX?detail_view=true
    darwin_nfx: https://www.darwinex.com/darwin/NFX?detail_view=true
    twitter: http://twitter.com/integracore2
    linkedin: https://www.linkedin.com/in/ali-saif/
    github: https://github.com/integracore2
    roles:
        - Technical Architect & Trainer
        - Multi-Cloud Solutions Architect
        - Software Engineer & Developer Advocate
        - Startup Advisor & Corporate Trainer
        - Buy-Side Quant & Algorithmic Trader
    datacamp: 
        profile: https://www.datacamp.com/profile/integracore
    udacity:
        aitrading: https://confirm.udacity.com/5DVTP4V7
    aws:
        ccp: https://www.credly.com/badges/bb4a9846-1b3d-4df1-a104-ba62e2835386?source=linked_in_profile
        well_architected_framework: https://aws.amazon.com/architecture/well-architected/

fun_facts:
    entries:
        1:
            title: Happy Clients
            value: 578
            icon: heart
        2:
            title: Working Hours
            value: 4,780
            icon: clock
        3:
            title: Awards Won
            value: 15
            icon: star
        4:
            title: Coffee Consumed
            value: 1,286
            icon: cup

google_recaptcha:
    site_key: 6LeNlGcgAAAAAI-k3G6BDl_dixxmXKMbIFS8WZih

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: