# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Saif
tagline:          'Quant by day, guitarist by night..'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://integracore2.github.io
baseurl:          /

author:
  name:           'integracore2'
  url:            https://twitter.com/integracore2

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/integracore2
