title: Saif
logo: /assets/img/logo.png
description: Full-Stack Data Scientist / Resident Growth Hacker @ Darwinex
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
author:
    name: Saif (integracore2)