title: Ali Saif
logo: 
    image: /assets/img/profile-picture.jpg
    symbol: "&Lambda;"
    text: "Ali <span>Saif</span>"
description: Contract Consultant | Technical Architect | Startup Advisor
show_downloads: false
#paginate: 5
google_analytics:
# theme: jekyll-theme-integracore2-light
google_recaptcha:
    site_key: 6LeNlGcgAAAAAI-k3G6BDl_dixxmXKMbIFS8WZih

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: