page:
  title: Experience
  subtitle: "<i>~ evolving relentlessly since 1997 ~</i>"

engagements:
  title: Engagements

education:
  title: Education

certifications:
  title: Certifications

courses:
  title: Courses

datacamp: 
  image_url: /assets/img/datacamp-courses.png
  profile: https://www.datacamp.com/profile/integracore