page:
  title: Experience
  subtitle: "<i>~ evolving relentlessly since 1997 ~</i>"
engagements:
  title: Engagements
education:
  title: Education
datacamp: 
        profile: https://www.datacamp.com/profile/integracore
udacity:
    aitrading: https://confirm.udacity.com/5DVTP4V7
aws:
    ccp: https://www.credly.com/badges/bb4a9846-1b3d-4df1-a104-ba62e2835386?source=linked_in_profile