page:
  title: Innovations
  subtitle: "<i>~ evolving relentlessly since 1997 ~</i>"

categories:
  
  titles:
    strategies: Systematic Trading Strategy Portfolios
    opensource: Open Source Contributions
  
  item_types:
    strategies: video_youtube
    opensource: direct_url
  
  data:
    opensource:
      -
        name: All
        data_group: all # this must match with any video's category.slug in content.yml
        enabled: true
      -
        name: Integrations Engineering
        data_group: integractions-engineering
        enabled: true
      -
        name: API Development
        data_group: api-development
        enabled: true
        
    strategies:
      -
        name: All
        data_group: all # this must match with any video's category.slug in content.yml
        enabled: true
      -
        name: Mean Reversion Trading
        data_group: mean-reversion-trading-strategies
        enabled: true
      -
        name: Volatility Trading
        data_group: volatility-trading-strategies
        enabled: true