page:
  title: Publications
  subtitle: "<i>~ evolving relentlessly since 1997 ~</i>"

categories:
  -
    name: All
    data_group: category_all
    enabled: true
  -
    name: Detailed
    data_group: category_detailed
    enabled: true
  -
    name: Direct URL
    data_group: category_direct-url
    enabled: true
  -
    name: Image
    data_group: category_image
    enabled: true
  -
    name: SoundCloud
    data_group: category_soundcloud
    enabled: true
  -
    name: Video
    data_group: category_video
    enabled: true
  -
    name: Vimeo Video
    data_group: category_vimeo-video
    enabled: true
  -
    name: YouTube Video
    data_group: category_youtube-video
    enabled: true
  

item_types:
  image:
    category: Image
    classes:
      item: lbimage
      link: lightbox
      fa: fa fa-image
  video:
    youtube:
      category: Video, YouTube Video
      classes:
        item: lbvideo
        link: lightbox mfp-iframe
        fa: fab fa-youtube
    vimeo:
      category: Video, Vimeo Video
      classes:
        item: lbvideo
        link: lightbox mfp-iframe
        fa: fab fa-vimeo-v
  audio:
    soundcloud:
      category: SoundCloud
      classes:
        item: lbaudio
        link: lightbox mfp-iframe
        fa: fas fa-volume-up
  project:
    category: Detailed
    classes:
      item: standard      
      link: ajax-page-load
      fa: far fa-file-alt
  direct_url:
    category: Direct URL
    classes:
      item: direct
      link: ""
      fa: fa fa-link